### ISSUE TITLE
Resizing QCOW2 disk fails

### ISSUE THREAD

**Issue by IlanZuckerman** [oVirt/ovirt-ansible-image-template#53]
Hi, I am running the role against our RHV-M 4.3.7.0-0.1.el7 on rhel 7
The role fails to resize the QCOW2 disk which is being attached to the vm.
The Failure occures in "Resize disk if smaller than template_disk_size" task at roles/ovirt-ansible-image-template/tasks/qcow2_image.yml:174
It simply runs out of retries. I tried to increase retries amount - didnt help.

**Ansible log:**

`        "fatal: [rhev-red-01.rdu2.scalelab.redhat.com]: FAILED! => {", 
        "    \"attempts\": 40, ", 
        "    \"changed\": false, ", 
        "    \"diff\": {", 
        "        \"after\": {}, ", 
        "        \"before\": {}", 
        "    }, ", 
        "    \"disk\": {", 
        "        \"actual_size\": 11811160064, ", 
        "        \"alias\": \"basic_regression_43\", ", 
        "        \"backup\": \"none\", ", 
        "        \"content_type\": \"data\", ", 
        "        \"description\": \"\", ", 
        "        \"disk_profile\": {", 
        "            \"href\": \"/ovirt-engine/api/diskprofiles/7911291e-1909-4e54-a349-d914398ddd32\", ", 
        "            \"id\": \"7911291e-1909-4e54-a349-d914398ddd32\"", 
        "        }, ", 
        "        \"format\": \"cow\", ", 
        "        \"href\": \"/ovirt-engine/api/disks/9519859c-aee8-46d2-b75b-d32f171e109f\", ", 
        "        \"id\": \"9519859c-aee8-46d2-b75b-d32f171e109f\", ", 
        "        \"image_id\": \"b59bfa7b-448e-45d9-952d-e92ea9ae8658\", ", 
        "        \"name\": \"basic_regression_43\", ", 
        "        \"permissions\": [], ", 
        "        \"propagate_errors\": false, ", 
        "        \"provisioned_size\": 10737418240, ", 
        "        \"qcow_version\": \"qcow2_v2\", ", 
        "        \"quota\": {", 
        "            \"href\": \"/ovirt-engine/api/datacenters/95e81cc4-f975-11e9-bb04-02e6ef0f2614/quotas/9f9566b4-f975-11e9-926f-02e6ef0f2614\", ", 
        "            \"id\": \"9f9566b4-f975-11e9-926f-02e6ef0f2614\"", 
        "        }, ", 
        "        \"shareable\": false, ", 
        "        \"sparse\": true, ", 
        "        \"statistics\": [], ", 
        "        \"status\": \"ok\", ", 
        "        \"storage_domains\": [", 
        "            {", 
        "                \"href\": \"/ovirt-engine/api/storagedomains/125fd708-2dc9-4118-b03e-e602840e086c\", ", 
        "                \"id\": \"125fd708-2dc9-4118-b03e-e602840e086c\"", 
        "            }", 
        "        ], ", 
        "        \"storage_type\": \"image\", ", 
        "        \"total_size\": 11811160064, ", 
        "        \"wipe_after_delete\": true", 
        "    }, ", 
        "    \"id\": \"9519859c-aee8-46d2-b75b-d32f171e109f\", ", 
        "    \"invocation\": {", 
        "        \"module_args\": {", 
        "            \"activate\": null, ", 
        "            \"auth\": {", 
        "                \"ca_file\": null, ", 
        "                \"compress\": true, ", 
        "                \"headers\": null, ", 
        "                \"insecure\": true, ", 
        "                \"kerberos\": false, ", 
        "                \"timeout\": 0, ", 
        "                \"token\": \"27H4D1Q3b755JV7tQkBhEWp7DzF9VgojmDcuzIThoG_EdVTYog_opHGujBz7VAmufQE9T2j5R5H50ypt2FFdwg\", ", 
        "                \"url\": \"https://rhev-red-01.rdu2.scalelab.redhat.com/ovirt-engine/api\"", 
        "            }, ", 
        "            \"bootable\": null, ", 
        "            \"content_type\": \"data\", ", 
        "            \"description\": null, ", 
        "            \"download_image_path\": null, ", 
        "            \"fetch_nested\": false, ", 
        "            \"force\": false, ", 
        "            \"format\": \"cow\", ", 
        "            \"host\": null, ", 
        "            \"id\": \"9519859c-aee8-46d2-b75b-d32f171e109f\", ", 
        "            \"image_provider\": null, ", 
        "            \"interface\": null, ", 
        "            \"logical_unit\": null, ", 
        "            \"name\": null, ", 
        "            \"nested_attributes\": [], ", 
        "            \"openstack_volume_type\": null, ", 
        "            \"poll_interval\": 3, ", 
        "            \"profile\": null, ", 
        "            \"quota_id\": null, ", 
        "            \"shareable\": null, ", 
        "            \"size\": null, ", 
        "            \"sparse\": null, ", 
        "            \"sparsify\": null, ", 
        "            \"state\": \"present\", ", 
        "            \"storage_domain\": null, ", 
        "            \"storage_domains\": null, ", 
        "            \"timeout\": 180, ", 
        "            \"upload_image_path\": null, ", 
        "            \"vm_id\": null, ", 
        "            \"vm_name\": null, ", 
        "            \"wait\": true, ", 
        "            \"wipe_after_delete\": null", 
        "        }", 
        "    }", 
        "}", 
        "", 
`

**Engine log:**

`2019-10-31 04:19:12,768-04 INFO  [org.ovirt.engine.core.vdsbroker.irsbroker.SPMClearTaskVDSCommand] (EE-ManagedThreadFactory-engine-Thread-64161) [] FINISH, SPMClearTaskVDSCommand, return: , log id: 384b8006
2019-10-31 04:19:12,772-04 INFO  [org.ovirt.engine.core.bll.tasks.SPMAsyncTask] (EE-ManagedThreadFactory-engine-Thread-64161) [] BaseAsyncTask::removeTaskFromDB: Removed task 'aaf44347-940e-492b-a17e-8cd949a1dcf3' from DataBase
2019-10-31 04:19:12,772-04 INFO  [org.ovirt.engine.core.bll.tasks.CommandAsyncTask] (EE-ManagedThreadFactory-engine-Thread-64161) [] CommandAsyncTask::HandleEndActionResult [within thread]: Removing CommandMultiAsyncTasks object for entity 'f376fb0d-a2a8-4cc2-9bc3-82c42916129e'
2019-10-31 04:19:12,855-04 ERROR [org.ovirt.engine.core.vdsbroker.vdsbroker.PrepareImageVDSCommand] (EE-ManagedThreadFactory-engineScheduled-Thread-42) [7004c860-e4e6-42c5-9f18-eda83462c4e4] Failed in 'PrepareImageVDS' method, for vds: 'f02-h19-000-r620'; host: 'f02-h19-000-r620.rdu2.scalelab.redhat.com': null
2019-10-31 04:19:12,855-04 ERROR [org.ovirt.engine.core.vdsbroker.vdsbroker.PrepareImageVDSCommand] (EE-ManagedThreadFactory-engineScheduled-Thread-42) [7004c860-e4e6-42c5-9f18-eda83462c4e4] Command 'PrepareImageVDSCommand(HostName = f02-h19-000-r620, PrepareImageVDSCommandParameters:{hostId='f63e93d4-44d3-4f13-be24-f3d4da3b2eeb'})' execution failed: null
2019-10-31 04:19:12,855-04 INFO  [org.ovirt.engine.core.vdsbroker.vdsbroker.PrepareImageVDSCommand] (EE-ManagedThreadFactory-engineScheduled-Thread-42) [7004c860-e4e6-42c5-9f18-eda83462c4e4] FINISH, PrepareImageVDSCommand, return: , log id: 535e04dc
2019-10-31 04:19:12,855-04 ERROR [org.ovirt.engine.core.bll.storage.disk.image.TransferDiskImageCommand] (EE-ManagedThreadFactory-engineScheduled-Thread-42) [7004c860-e4e6-42c5-9f18-eda83462c4e4] Unable to update the image info for image 'b59bfa7b-448e-45d9-952d-e92ea9ae8658' (image group: '9519859c-aee8-46d2-b75b-d32f171e109f') on domain '125fd708-2dc9-4118-b03e-e602840e086c'
2019-10-31 04:19:12,868-04 INFO  [org.ovirt.engine.core.bll.storage.disk.image.TransferDiskImageCommand] (EE-ManagedThreadFactory-engineScheduled-Thread-42) [7004c860-e4e6-42c5-9f18-eda83462c4e4] Successfully transferred disk '00000000-0000-0000-0000-000000000000' (command id '77c689d8-336c-4536-a0a1-956bd723a9df')
2019-10-31 04:19:12,869-04 INFO  [org.ovirt.engine.core.bll.storage.disk.image.TransferDiskImageCommand] (EE-ManagedThreadFactory-engineScheduled-Thread-42) [7004c860-e4e6-42c5-9f18-eda83462c4e4] Ending command 'org.ovirt.engine.core.bll.storage.disk.image.TransferDiskImageCommand' successfully.
2019-10-31 04:19:12,871-04 INFO  [org.ovirt.engine.core.vdsbroker.irsbroker.GetImageInfoVDSCommand] (EE-ManagedThreadFactory-engineScheduled-Thread-42) [7004c860-e4e6-42c5-9f18-eda83462c4e4] START, GetImageInfoVDSCommand( GetImageInfoVDSCommandParameters:{storagePoolId='95e81cc4-f975-11e9-bb04-02e6ef0f2614', ignoreFailoverLimit='false', storageDomainId='125fd708-2dc9-4118-b03e-e602840e086c', imageGroupId='9519859c-aee8-46d2-b75b-d32f171e109f', imageId='b59bfa7b-448e-45d9-952d-e92ea9ae8658'}), log id: a92756b

2019-10-31 04:27:35,331-04 INFO  [org.ovirt.engine.core.vdsbroker.vdsbroker.ConnectStorageServerVDSCommand] (EE-ManagedThreadFactory-engine-Thread-64296) [47eba1ca] FINISH, ConnectStorageServerVDSCommand, return: {68af3741-9de8-4a7f-887b-854d811cfcdf=0}, log id: 622489df
2019-10-31 04:27:35,333-04 INFO  [org.ovirt.engine.core.vdsbroker.irsbroker.AttachStorageDomainVDSCommand] (default task-172) [57a54ae3-6dee-47c1-b523-37739e370388] START, AttachStorageDomainVDSCommand( AttachStorageDomainVDSCommandParameters:{storagePoolId='95e81cc4-f975-11e9-bb04-02e6ef0f2614', ignoreFailoverLimit='false', storageDomainId='6f0b8a94-d745-4fb2-b280-12e39939fdf8'}), log id: 7dd50d1f
2019-10-31 04:27:56,962-04 INFO  [org.ovirt.engine.core.vdsbroker.irsbroker.AttachStorageDomainVDSCommand] (default task-172) [57a54ae3-6dee-47c1-b523-37739e370388] FINISH, AttachStorageDomainVDSCommand, return: , log id: 7dd50d1f
2019-10-31 04:27:56,977-04 ERROR [org.ovirt.engine.core.bll.storage.domain.AttachStorageDomainToPoolCommand] (default task-172) [] An error occurred while fetching unregistered disks from Storage Domain id '6f0b8a94-d745-4fb2-b280-12e39939fdf8'
2019-10-31 04:27:56,991-04 INFO  [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (default task-172) [] EVENT_ID: USER_ATTACH_STORAGE_DOMAIN_TO_POOL(962), Storage Domain guest_tools_iso was attached to Data Center Default by admin@internal-authz
2019-10-31 04:27:56,994-04 INFO  [org.ovirt.engine.core.bll.storage.domain.AttachStorageDomainToPoolCommand] (default task-172) [] Lock freed to object 'EngineLock:{exclusiveLocks='[6f0b8a94-d745-4fb2-b280-12e39939fdf8=STORAGE]', sharedLocks=''}'
2019-10-31 04:28:07,328-04 INFO  [org.ovirt.engine.core.bll.storage.domain.ActivateStorageDomainCommand] (default task-172) [064c1a43-7335-455a-933d-679ec35a05ae] Lock Acquired to object 'EngineLock:{exclusiveLocks='[6f0b8a94-d745-4fb2-b280-12e39939fdf8=STORAGE]', sharedLocks=''}'`

**vdsm log:**

`2019-10-31 08:22:27,285+0000 INFO  (jsonrpc/7) [jsonrpc.JsonRpcServer] RPC call Task.clear succeeded in 0.01 seconds (__init__:312)
2019-10-31 08:22:27,370+0000 INFO  (jsonrpc/3) [vdsm.api] FINISH prepareImage error=Command ['/usr/bin/qemu-img', 'info', '--output', 'json', '-U', u'/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658'] failed with rc=1 out='' err="qemu-img: Could not open '/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658': Could not open '/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658': No such file or directory\n" from=::ffff:10.1.41.200,59580, flow_id=7004c860-e4e6-42c5-9f18-eda83462c4e4, task_id=65099c4f-f2c8-44c9-96ed-623e26543475 (api:52)
2019-10-31 08:22:27,370+0000 ERROR (jsonrpc/3) [storage.TaskManager.Task] (Task='65099c4f-f2c8-44c9-96ed-623e26543475') Unexpected error (task:875)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vdsm/storage/task.py", line 882, in _run
    return fn(*args, **kargs)
  File "<string>", line 2, in prepareImage
  File "/usr/lib/python2.7/site-packages/vdsm/common/api.py", line 50, in method
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/vdsm/storage/hsm.py", line 3216, in prepareImage
    dom.produceVolume(imgUUID, volUUID).updateInvalidatedSize()
  File "/usr/lib/python2.7/site-packages/vdsm/storage/volume.py", line 1432, in updateInvalidatedSize
    self._manifest.updateInvalidatedSize()
  File "/usr/lib/python2.7/site-packages/vdsm/storage/volume.py", line 510, in updateInvalidatedSize
    qemu_info = qemuimg.info(self.getVolumePath(), unsafe=True)
  File "/usr/lib/python2.7/site-packages/vdsm/storage/qemuimg.py", line 113, in info
    out = _run_cmd(cmd)
  File "/usr/lib/python2.7/site-packages/vdsm/storage/qemuimg.py", line 463, in _run_cmd
    raise cmdutils.Error(cmd, rc, out, err)
Error: Command ['/usr/bin/qemu-img', 'info', '--output', 'json', '-U', u'/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658'] failed with rc=1 out='' err="qemu-img: Could not open '/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658': Could not open '/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658': No such file or directory\n"
2019-10-31 08:22:27,370+0000 INFO  (jsonrpc/3) [storage.TaskManager.Task] (Task='65099c4f-f2c8-44c9-96ed-623e26543475') aborting: Task is aborted: u'Command [\'/usr/bin/qemu-img\', \'info\', \'--output\', \'json\', \'-U\', u\'/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658\'] failed with rc=1 out=\'\' err="qemu-img: Could not open \'/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658\': Could not open \'/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658\': No such file or directory\\n"' - code 100 (task:1181)
2019-10-31 08:22:27,371+0000 ERROR (jsonrpc/3) [storage.Dispatcher] FINISH prepareImage error=Command ['/usr/bin/qemu-img', 'info', '--output', 'json', '-U', u'/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658'] failed with rc=1 out='' err="qemu-img: Could not open '/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658': Could not open '/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658': No such file or directory\n" (dispatcher:87)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vdsm/storage/dispatcher.py", line 74, in wrapper
    result = ctask.prepare(func, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/vdsm/storage/task.py", line 108, in wrapper
    return m(self, *a, **kw)
  File "/usr/lib/python2.7/site-packages/vdsm/storage/task.py", line 1189, in prepare
    raise self.error
Error: Command ['/usr/bin/qemu-img', 'info', '--output', 'json', '-U', u'/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658'] failed with rc=1 out='' err="qemu-img: Could not open '/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658': Could not open '/rhev/data-center/mnt/blockSD/125fd708-2dc9-4118-b03e-e602840e086c/images/9519859c-aee8-46d2-b75b-d32f171e109f/b59bfa7b-448e-45d9-952d-e92ea9ae8658': No such file or directory\n"
`

**Comment by mnecas** [comment]
Hi @IlanZuckerman, 
there was already a similar issue #46 it should be fixed in version 1.1.12
try to update it and change variable `disk_resize_timeout` to larger, which indicates the number of retries. 
Hope it will help if not please don't hesitate to inform us.

**Comment by briantward** [comment]
I ran into this one... but bumping `disk_resize_timeout: 600` on 1.1.12 worked well enough for me.
